apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: luizpedrojf/gitops
  newTag: ab3acdc0a01e2fa3704cb101c590868cea45e1e0
